[package]
name = "squidge"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1.2.1"
derive_more = "0.99.13"
enumflags2 = "0.7.1"
nom = "6.1.2"
